const r = require('express').Router();
const c = require('../controllers/template.controller');
const { protect } = require('../middleware/auth');
r.use(protect);
r.get('/', c.list);
r.post('/', c.create);
r.get('/:id', c.getOne);
r.put('/:id', c.update);
r.delete('/:id', c.remove);
module.exports = r;
